booking/urls.py
from django.urls import path
from .views import available_cars, book_car,view_bookings,search_cars,cancel_booking,payment,submit_review

urlpatterns = [
    path('available-cars/', available_cars, name='available_cars'),
    path('search-cars/', search_cars, name='search_cars'),
    path('bookings/<int:car_id>/', book_car, name='bookings'),
    path('view_bookings/', view_bookings, name='view_bookings'),
    path('cancel_booking/', cancel_booking, name='cancel_booking'),
    path('submit_review/<int:car_id>', submit_review, name='submit_review'),
    path('payment/<int:car_id>/<str:pickup_datetime>/<str:dropoff_datetime>/<str:total_price>/', payment, name='payment'),

    # Add other URLs here if needed
]

vroom/urls.py
from django.contrib import admin
from django.urls import path,include

from accounts import views as auth_view
from . import views
from django.contrib.auth import views as pass_view
from django.conf.urls.static import static
from django.conf import settings
from .views import CustomPasswordResetView

from booking.views import contact
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('signup/', auth_view.signup, name='signup'),
    path('login/', auth_view.login_view, name='login'),
    path('logout/', auth_view.logout_view, name='logout'),
    path('about/', views.about, name='about'),
    path('faq/', views.faq, name='faq'),
    # path('password-reset/', 
    #      pass_view.PasswordResetView.as_view(template_name = 'resetpass.html'), 
    #      name='password_reset'),
    path('password-reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', 
         pass_view.PasswordResetDoneView.as_view(template_name = 'resetpass_done.html'), 
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', 
         pass_view.PasswordResetConfirmView.as_view(template_name = 'resetpass_confirm.html'), 
         name='password_reset_confirm'),
    path('password-reset-complete/', 
         pass_view.PasswordResetCompleteView.as_view(template_name = 'resetpass_done_complete.html'), 
         name='password_reset_complete'),

    path('cars/', include('booking.urls')),
    path('account/', include('accounts.urls')),
    
    path('search/', views.search, name='search'),
    path('contact/', contact, name='contact'),

    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booking/forms.py
from django import forms
from .models import Review

class CarSearchForm(forms.Form):
    # pickup_datetime = forms.DateTimeField(label='Pickup Date and Time', widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))
    pickup_datetime = forms.DateTimeField(label='Pickup Date and Time')
    # dropoff_datetime = forms.DateTimeField(label='Drop-off Date and Time', widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))
    dropoff_datetime = forms.DateTimeField(label='Drop-off Date and Time')

    location = forms.ChoiceField(label='Location', choices=[('Kathmandu','Kathmandu'),('Pokhara','Pokhara')], widget=forms.Select)



class ReviewForm(forms.ModelForm):
    rating = forms.ChoiceField(choices=[(i, i) for i in range(1, 6)], widget=forms.RadioSelect)

    class Meta:
        model = Review
        fields = ['content', 'rating']

from django import forms

class ContactForm(forms.Form):
    title = forms.CharField(max_length=100)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

booking/views.py
from django.shortcuts import render
from .forms import CarSearchForm
from .models import Car
from decimal import Decimal
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages  # Import messages framework
from django.shortcuts import redirect
from .models import Booking, Car
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.mail import send_mail
from vroom.settings import EMAIL_HOST_USER
from django.urls import reverse
from django.http import HttpResponseRedirect

from accounts.models import IDVerification
from accounts.models import Favourite


def search_cars(request):
    if request.method == 'POST':
        form = CarSearchForm(request.POST)
        if form.is_valid():
            pickup_datetime = form.cleaned_data['pickup_datetime']
            dropoff_datetime = form.cleaned_data['dropoff_datetime']
            location = form.cleaned_data['location']

            # Query available cars within the specified date range and location
            available_cars = Car.objects.filter(
                # availability='available',
                car_location=location
            )

            # Calculate duration in hours
            duration_hours = Decimal((dropoff_datetime - pickup_datetime).total_seconds()) / Decimal(3600)

            # Calculate price for each car
            for car in available_cars:
                car.total_price = round(duration_hours * car.hourly_rate, 2)
            
            return render(request, 'available_cars.html', {'cars': available_cars})
    else:
        form = CarSearchForm()
    
    return render(request, 'Vroom.html', {'form': form})

def available_cars(request):
    cars = Car.objects.all()

    car_location = request.GET.getlist('car_location')
    type = request.GET.getlist('type')
    availability = request.GET.getlist('availability')
    query = request.GET.get('q', '')  # Use an empty string as the default value

    print(car_location)

    # if request.GET:
    if 'q' in request.GET:  # Add this line to apply the search query filter
        cars = cars.filter(model__icontains=query)
    if 'car_location' in request.GET:
        cars = cars.filter(car_location__in=car_location)
    if 'type' in request.GET:
        cars = cars.filter(type__in=type)
    if 'availability' in request.GET:
        cars = cars.filter(availability__in=availability)
        

    return render(request, 'availablecar.html', {
        'cars': cars,
        'car_location': car_location,
        'type': type,
        'availability': availability,
        'query': query, 
        # Pass other context variables as needed
    })

@login_required(login_url='login')
def book_car(request, car_id):
    # car = Car.objects.prefetch_related('reviews').get(id=car_id)
    
    car = get_object_or_404(Car, id=car_id)
    approved_reviews = car.reviews.filter(approved=True)
    
    # Check if the user is verified
    try:
        id_verification = IDVerification.objects.get(user=request.user)
        id_verification_status = id_verification.status == 'verified'
    except IDVerification.DoesNotExist:
        id_verification_status = False
    
    # Check if the user has already booked this car
    if Booking.objects.filter(user=request.user, car=car, status='pending').exists():
        return render(request, 'booking.html', {'car': car, 'message': 'You have already booked this car.', 'isbooked': True,'reviews': approved_reviews})
    
    if request.method == 'POST':
        form = CarSearchForm(request.POST)
        if form.is_valid():
            pickup_datetime = form.cleaned_data['pickup_datetime']
            dropoff_datetime = form.cleaned_data['dropoff_datetime']

            duration_hours = Decimal((dropoff_datetime - pickup_datetime).total_seconds()) / Decimal(3600)
            total_price = round(duration_hours * car.hourly_rate, 2)

            # Convert pickup_datetime and dropoff_datetime to strings
            pickup_datetime_str = pickup_datetime.strftime('%Y-%m-%d %H:%M:%S')
            dropoff_datetime_str = dropoff_datetime.strftime('%Y-%m-%d %H:%M:%S')

            # Create a context dictionary
            context = {
                'car': car,
                'pickup_datetime': pickup_datetime_str,
                'dropoff_datetime': dropoff_datetime_str,
                'total_price': total_price,
            }

            # Redirect to the payment page with necessary data
            return render(request, 'payment.html', context)
        
    else:
        form = CarSearchForm()
    return render(request, 'booking.html', {'car': car,'form':form, 'id_verification_status': id_verification_status, 'reviews': approved_reviews})

@login_required(login_url='login')
def view_bookings(request):
    bookings = Booking.objects.filter(user=request.user).order_by('-booking_date')
    favourites = Favourite.objects.filter(user=request.user)
    try:
        id_verification = IDVerification.objects.get(user=request.user)
        id_verification_status = id_verification.status == 'verified'
    except IDVerification.DoesNotExist:
        id_verification_status = False
    return render(request, 'userprofile.html', {'bookings': bookings, 'user': request.user, 'id_verification_status': id_verification_status, 'favourites': favourites})


from django.utils import timezone
from datetime import timedelta
from decimal import Decimal

@csrf_exempt
def cancel_booking(request):
    if request.method == 'POST':
        booking_id = request.POST.get('booking_id')
        booking = Booking.objects.get(id=booking_id)

        # Check if the current time is more than 3 hours from the booking time
        if timezone.now() > booking.booking_date + timedelta(hours=3):
            # Deduct 20% from the payment
            booking.estimated_price *=  Decimal('0.2')

        else:
            booking.estimated_price = 0
        # Change the booking status to 'rejected'
        booking.status = 'cancelled'
        # Save the changes
        booking.save()

        return JsonResponse({'status':'ok'})
        
    else:
        return JsonResponse({'status':'error'})
    
from django.contrib import messages

from django.shortcuts import render, get_object_or_404
from django.core.mail import send_mail
from .models import Booking, Car

def payment(request, car_id, pickup_datetime, dropoff_datetime, total_price):
    car = get_object_or_404(Car, id=car_id)

    if request.method == 'POST':
        # Check if a booking already exists
        existing_booking = Booking.objects.filter(user=request.user, car=car, pick_up_date=pickup_datetime, drop_off_date=dropoff_datetime,status='pending').exists()

        if existing_booking:
            # Render the payment page with an error message
            return render(request, 'payment.html', {'car': car, 'pickup_datetime': pickup_datetime, 'dropoff_datetime': dropoff_datetime, 'total_price': total_price, 'error_message': 'You have already booked this car for the selected time range.'})
        else:
            # Create the booking
            Booking.objects.create(user=request.user, car=car, status='pending', estimated_price=total_price, drop_off_date=dropoff_datetime, pick_up_date=pickup_datetime)

            # Send an email to the user
            send_mail(
                f'Booking Successful for Car {car.model} on {pickup_datetime}',
                f'''Your booking has been successful and waiting confiramation by the dealer.
                Car: {car.model}.
                For date {pickup_datetime} to {dropoff_datetime}.
                Total Price: {total_price}.\n
                Thank you for booking with us.
                ''',
                EMAIL_HOST_USER,
                [request.user.email],
                fail_silently=False,
            )

            # Render the payment page with the success message
            return render(request, 'payment.html', {'car': car, 'pickup_datetime': pickup_datetime, 'dropoff_datetime': dropoff_datetime, 'total_price': total_price, 'booking_confirmed': True})

    # Render the payment page
    return render(request, 'payment.html', {'car': car, 'pickup_datetime': pickup_datetime, 'dropoff_datetime': dropoff_datetime, 'total_price': total_price})



from .forms import ReviewForm
from .models import Car  # Import the Car model

def submit_review(request, car_id):
    car = Car.objects.get(id=car_id)  # Retrieve the car from the database
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.car = car  # Set the car of the review
            review.save()
            return redirect('view_bookings')
    else:
        form = ReviewForm()
    return render(request, 'submit_review.html', {'form': form, 'car': car})  # Pass the car to the template


from django.core.mail import send_mail
from django.shortcuts import render
from .forms import ContactForm
from accounts.models import CustomUser

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']

            # Fetch all admin emails
            admin_emails = CustomUser.objects.filter(is_staff=True).values_list('email', flat=True)

            send_mail(
                f'From - {email} | {title}',
                f'From - {email} \n {message}',
                email,
                admin_emails,
                fail_silently=True,
            )

            return render(request, 'contact.html', {'form': form, 'success': True})

    else:
        form = ContactForm()

    return render(request, 'contact.html', {'form': form})

vroom/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import redirect
from booking.models import Booking, Car
from booking.forms import CarSearchForm
from decimal import Decimal
from booking.models import Car
from django.db.models import Count

# Home Page
def home(request):
    if request.method == 'POST':
        form = CarSearchForm(request.POST)
        if form.is_valid():
            pickup_datetime = form.cleaned_data['pickup_datetime']
            dropoff_datetime = form.cleaned_data['dropoff_datetime']
            location = form.cleaned_data['location']

            # Query available cars within the specified date range and location
            available_cars = Car.objects.filter(
                availability='available',
                car_location=location
            )

            # Calculate duration in hours
            duration_hours = Decimal((dropoff_datetime - pickup_datetime).total_seconds()) / Decimal(3600)

            # Calculate price for each car
            for car in available_cars:
                car.total_price = round(duration_hours * car.hourly_rate, 2)
                
            return render(request, 'availablecar.html', {'cars': available_cars})
    else:
        form = CarSearchForm()
    
    # Sort 3 featured cars (most expensive)
    featured_cars = Car.objects.filter(
        availability='available'
    ).order_by('-hourly_rate')[:3]

    # Sort 3 popular cars (most booked)
    popular_cars = Car.objects.filter(
        availability='available'
    ).annotate(
        num_bookings=Count('booking')  # Use 'booking' to count the number of Booking instances for each Car
    ).order_by('-num_bookings')[:3]


    return render(request, 'Vroom.html', {'form': form,'featured_cars': featured_cars,'popular_cars': popular_cars})

def search(request):
    car_location = request.GET.getlist('car_location')
    type = request.GET.getlist('type')
    availability = request.GET.getlist('availability')

    query = request.GET.get('q', '')  # Use an empty string as the default value
    results = Car.objects.all()

    if query:
        results = results.filter(model__icontains=query)
        if results and car_location:
            results = results.filter(car_location__in=car_location)
        if results and type:
            results = results.filter(type__in=type)
        if results and availability:
            results = results.filter(availability__in=availability)

    return render(request, 'availablecar.html', {
        'cars': results, 
        'query': query, 
        'car_location': car_location,
        'type': type,
        'availability': availability,
    })

# About Page
def about(request):
    return render(request,'about.html')

# FAQ Page
def faq(request):
    return render(request,'faq.html')


from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from django.contrib.auth import get_user_model

User = get_user_model()
class CustomPasswordResetView(PasswordResetView):
    template_name = 'resetpass.html'  # replace with your template path

    def form_valid(self, form):
        email = form.cleaned_data.get('email')
        if not User.objects.filter(email=email).exists():
            form.add_error('email', ValidationError('Email not found in database.', code='email'))
            return self.form_invalid(form)
        return super().form_valid(form)

    def form_invalid(self, form):
        return render(self.request, self.template_name, {'form': form})

templates/Vroom.html
{% extends "base.html" %}
{% load static %}


{% block head %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'style.css' %}">
<link rel="stylesheet" href="{% static 'alert.css' %}">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
  integrity="sha512-Fo3rlrZj/k79vwqGsfqMVcSurYfZu6J362uvF0owHoaVAUkE/DunR0lCjxZKDtdRn2U6U6JUkyD/rEaUB8JpB5wDtmSgA=="
  crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.6.13/flatpickr.min.css">

<title>Vroom Car Rental</title>
{% endblock %}

{% block content %}

<div class="booking-container" style="background-image: url({% static 'lc.png' %});">
  <div class="container">
    <h2>Better way to rent your car</h2>
    <div class="icon-container">
      <div>
        <img src="https://cdn-icons-png.flaticon.com/128/854/854929.png" alt="Location">
        <p>Pick Locations</p>
      </div>
      <div>
        <img src="https://cdn-icons-png.flaticon.com/128/15239/15239482.png" alt="Handshake">
        <p>Easy Transactions</p>
      </div>
      <div>
        <img src="https://cdn-icons-png.flaticon.com/128/7371/7371879.png" alt="Car">
        <p>Choose Your Car</p>
      </div>
    </div>
  </div>

  <div class="vertical-container">
    <h2>Book a Car</h2>

    <!-- Add this div for the error message -->
    <div class="errorMessage" style="color: red;"></div>

    <form method="post" id="carForm">
      {% csrf_token %}
      <p class="input-label">Pick Up Location</p>
      <select name="{{ form.location.name }}" id="id_location" class="location-dropdown">
        <option value="Kathmandu">Kathmandu</option>
        <option value="Pokhara">Pokhara</option>
      </select>
      <p class="input-label">Pick Up Date</p>
      <input type="text" name="{{ form.pickup_datetime.name }}" required="" id="id_pickup_datetime"
        class="date-input flatpickr">

      <p class="input-label">Drop Off Date</p>
      <input type="text" name="{{ form.dropoff_datetime.name }}" required="" id="id_dropoff_datetime"
        class="date-input flatpickr">

      <button type="submit">Rent a Car now</button>
    </form>

  </div>
</div>


<!-- Featured Cars Section -->
<div class="featured-cars">
  <h2>Featured Cars</h2>
  <div class="car-list">
    {% for car in featured_cars %}
    <div class="car">
      <img src="{{ car.image.url }}" alt="{{ car.model }}" width="100" />
      <h2>{{ car.model }}</h2>
      <h3>{{ car.type }}</h3>
      <p style="color: rgb(27, 27, 27);">Cost per hour : <strong>Rs {{ car.hourly_rate }}</strong></p>
      {% if car.total_price %}
      <p>Estimated : <strong>Rs {{ car.total_price }}</strong></p>
      {% endif %}

      <div style="display: flex; justify-content: space-between; align-items: center; height: 50px;">
        <a href="{% url 'bookings' car.id  %}"><button type="button"
            style="background-color: #007bff; border-radius: 8px; padding: 8px; color: white;">Book Now</button></a>
        <!-- <p class="availability {{ car.availability|lower }}">{{ car.availability }}</p> -->
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<div class="popular-rentals">
  <h2>Popular Rentals</h2>
  <div class="car-list">
    {% for car in popular_cars %}
    <div class="car">
      <img src="{{ car.image.url }}" alt="{{ car.model }}" width="100" />
      <h2>{{ car.model }}</h2>
      <h3>{{ car.type }}</h3>
      <p style="color: rgb(27, 27, 27);">Cost per hour : <strong>Rs {{ car.hourly_rate }}</strong></p>
      {% if car.total_price %}
      <p>Estimated : <strong>Rs {{ car.total_price }}</strong></p>
      {% endif %}

      <div style="display: flex; justify-content: space-between; align-items: center; height: 50px;">
        <a href="{% url 'bookings' car.id %}"><button type="button"
            style="background-color: #007bff; border-radius: 8px; padding: 8px; color: white;">Book Now</button></a>
        <!-- <p class="availability {{ car.availability|lower }}">{{ car.availability }}</p> -->
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<!-- Alert -->
<div class="modal-overlay" id="modalOverlay" style="display: none;"></div>

<div class="modal" id="errorModal" style="display: none;">
  <span class="modal-close-button" id="modalCloseButton">&times;</span>
  <h2>Error</h2>
  <p id="errorModalBody"></p>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.6.13/flatpickr.min.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script src="{% static 'Vroom.js' %}"></script>
<script src="{% static 'alert.js' %}"></script>


{% endblock %}

templates/availablecar.html
{% extends "base.html" %}
{% load static %}


{% block head %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Available Cars</title>

<link rel="stylesheet" href="{% static 'style.css' %}">
<link rel="stylesheet" href="{% static 'availablecar.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
  integrity="sha512-Fo3rlrZj/k79vwqGsfqMVcSurYfZu6J362uvF0owHoaVAUkE/DunR0lCjxZKDtdRn2U6U6JUkyD/rEaUB8JpB5wDtmSgA=="
  crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
{% endblock %}

{% block content %}

{% if query %}
<div class="title-container" style="margin-top: 100px;">
  <h2>Showing results for "{{ query }}"</h2>
</div>
{% else %}
<div class="car-slider">
  <img src="{% static 'BMW.png' %}" alt="" srcset="">
</div>

<div class="title-container available">
  <h1>Available Cars</h1>
</div>
{% endif %}

<div class="filter">
  <button onclick="toggleFilterMenu()">Filter</button>
</div>


<div class="content-container">
  <div id="filter-menu" class="filter-menu">
    <h2>Filter Options</h2>
    <form method="get">
      <h3>Location</h3>

      <input type="checkbox" name="car_location" value="Kathmandu" {% if 'Kathmandu' in car_location %}checked{% endif %}><label for="Kathmandu">Kathmandu</label><br>
      <input type="checkbox" name="car_location" value="Pokhara" {% if 'Pokhara' in car_location %}checked{% endif %}><label for="Pokhara">Pokhara</label><br>

      <!-- Add more locations as needed -->

      <h3>Type</h3>
      <input type="checkbox" name="type" value="Sedan" {% if 'Sedan' in type %}checked{% endif %}><label
        for="Sedan">Sedan</label><br>
      <input type="checkbox" name="type" value="SUV" {% if 'SUV' in type %}checked{% endif %}><label
        for="SUV">SUV</label><br>
      <input type="checkbox" name="type" value="Sports" {% if 'Sports' in type %}checked{% endif %}><label
        for="Sports">Sports</label><br>
      <input type="checkbox" name="type" value="EV" {% if 'EV' in type %}checked{% endif %}><label
        for="EV">EV</label><br>
      <input type="checkbox" name="type" value="MPV" {% if 'MPV' in type %}checked{% endif %}><label
        for="MPV">MPV</label><br>

      <!-- Add more types as needed -->

      <h3>Availability</h3>
      <input type="checkbox" name="availability" value="available" {% if 'available' in availability %}checked{% endif %}><label for="available">Available</label><br>
      <input type="checkbox" name="availability" value="unavailable" {% if 'unavailable' in availability %}checked{% endif %}><label for="unavailable">Unavailable</label><br>
      <input type="checkbox" name="availability" value="maintenance" {% if 'maintenance' in availability %}checked{% endif %}><label for="maintenance">Maintainance</label><br>


      <input type="hidden" name="q" value="{{ query }}">

      <button type="submit">Apply Filters</button>
      <button type="button" onclick="window.location.href=window.location.pathname;">Reset Filters</button>
    </form>
  </div>
  <div class="car-container">
    {% if cars %}
    {% for car in cars %}

    <div class="car">
      <img src="{{ car.image.url }}" alt="{{ car.model }}" width="100" />
      <h2>{{ car.model }}</h2>
      <h3>{{ car.type }}</h3>
      <p style="color: rgb(27, 27, 27);">Cost per hour : <strong>Rs {{ car.hourly_rate }}</strong></p>
      {% if car.total_price %}
      <p>Estimated : <strong>Rs {{ car.total_price }}</strong></p>
      {% endif %}
      <p style="color: rgb(27, 27, 27);">Location : <strong>{{ car.car_location }}</strong></p>

      <div class="car-book-button" style="display: flex; justify-content: space-between; align-items: center; height: 50px;">
        <a href="{% url 'bookings' car.id %}"><button type="button"
            style="background-color: #007bff; border-radius: 8px; padding: 8px; color: white;">Book Now</button></a>
        <p class="availability {{ car.availability|lower }}">{{ car.availability }}</p>
      </div>
    </div>

    {% endfor %}
    {% else %}
    <h1 style="margin-bottom: 50px;">No Car for your liking :</h1>
    {% endif %}
  </div>


</div>

<script src="{% static 'availablecar.js' %}"></script>
{% endblock %}

templates/booking_confirmation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking Confirmation</title>
</head>
<body>
    <h1>Booking Confirmation</h1>
    <p>Thank you for booking with us. Your booking is confirmed. You will receive an email shortly with further details.</p>
</body>
</html>

templates/contact_test.html
{% if success %}
    <p>Message sent successfully</p>
{% endif %}
{% if errors %}
    <ul>
        {% for error in errors %}
            <li>{{ error }}</li>
        {% endfor %}
    </ul>

{% endif %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Send</button>
</form>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Vroom - Login</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  <link rel="stylesheet" href="{% static 'login.css' %}">
  <link rel="stylesheet" href="{% static 'alert.css' %}">
  
  <style>
    .background {
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background-image: url('https://i.pinimg.com/originals/1f/44/3d/1f443dcf69acb29cd3b1d31d4826d303.jpg');
      background-size: cover;
      z-index: -1; /* Ensure background stays behind other content */
    }
  </style>
</head>

<body>
  <div class="background"></div> <!-- Add this div for the background image -->
  <div class="container">

    <form id="loginForm" class="form" method="POST" action="{% url 'login' %}">
      {% csrf_token %}
      <h2 style="margin-left: 250px; color: white;"> Login</h2>

      {% if messages %}
          {% for message in messages %}
              <div class="{{ message.tags }}Message">
                  {{ message }}
              </div>
          {% endfor %}
      {% endif %}

      <div class="form-control">
        <label for="{{ form.username.id_for_label}}"style="color: white;"><i class="fas fa-envelope" style="color: white;"></i> Email:</label>
        <input type="email" name="{{ form.username.name }}" class="form-control" />
        <span class="text-danger">{{ form.username.errors }}</span>
      </div>
      <div class="form-control">
        <label for="{{ form.password1.id_for_label}}"style="color: white;"><i class="fas fa-lock" style="color: white;"></i> Password:</label>
        <input type="password" name="{{ form.password.name }}" class="form-control" />
        <span class="text-danger">{{ form.password.errors }}</span>
      </div>
      <button type="submit">Login</button>
    </form>
    <p>Forgotten your Password? <a href="{% url 'password_reset' %}">Reset password</a></p>
    <p>Don't have an account? <a href="{% url 'signup' %}"> Sign up</a></p>
  </div>
  <!-- <script src="ls.js"></script> -->
</body>

</html>